language: node_js
node_js: "10.11.0"

matrix:
  include:
    - os: osx
    - os: linux
    # - os: windows

#osx_image: xcode9.1
osx_image: xcode10.2
  
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libx11-dev libxss-dev icnsutils graphicsmagick libappindicator1 libxtst-dev ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cinst -y python2; fi

branches:
  only:
    - master

cache: yarn
script: yarn test && yarn release

notifications:
  email:
    on_success: change
    on_failure: change

env:
  - YARN_GPG=no

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Colin Mitchell"
  - git config --local user.email "colin@muffinlabs.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  draft: true
  overwrite: true
  skip_cleanup: true
  # on:
  #   tags: true

