language: node_js
node_js: "10.11.0"

matrix:
  include:
    - os: osx
    - os: linux
    # - os: windows

#osx_image: xcode9.1
osx_image: xcode10.2
  
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libx11-dev libxss-dev icnsutils graphicsmagick libappindicator1 libxtst-dev ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cinst -y python2; fi

branches:
  only:
    - master

cache: yarn
script: yarn test && yarn release
#script: yarn release

notifications:
  email:
    on_success: change
    on_failure: change

env:
  - YARN_GPG=no
