language: node_js
node_js: "10.11.0"

matrix:
  include:
    - os: osx
    - os: linux
    # - os: windows

osx_image: xcode9.1
  
#env:
#  - ELECTRON_CACHE=$HOME/.cache/electron ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
  
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libx11-dev libxss-dev icnsutils graphicsmagick libappindicator1 libxtst-dev ; fi

branches:
  only:
    - master

cache: yarn
script: yarn release

notifications:
  email:
    on_success: never
    on_failure: change
