language: node_js
node_js: 12.4.0
matrix:
  include:
  - os: osx
  - os: linux
osx_image: xcode10.2
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libx11-dev libxss-dev
  icnsutils graphicsmagick libappindicator1 libxtst-dev ; fi
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cinst -y python2; fi
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.2
- export PATH="$HOME/.yarn/bin:$PATH"
branches:
  only:
  - master
cache: yarn
script:
- yarn test-lib && yarn release
- yarn test-ui
notifications:
  email:
    on_success: change
    on_failure: change
env:
  - YARN_GPG=no
