#
# NOTE: a bunch of things are actually setup on appveyor itself and
# not in this file. i'll try and document that at some point.
#
os: unstable

platform:
  - x64

cache:
  - "%LOCALAPPDATA%\\Yarn"
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

environment:
  matrix:
    - nodejs_version: '12.16.0'

image: Visual Studio 2019

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node $env:nodejs_version x64
  - set CI=true
  - git reset --hard HEAD
  - yarn

matrix:
  fast_finish: true

skip_commits:
  message: /\[ci\s+skip\]/
only_commits:
 message: /build/

# test: off
test_script:
  - node --version
  - yarn --version
  - yarn test --exit

build_script:
  - node --version
  - yarn release
