name: Run tests
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    env:
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      # https://stackoverflow.com/questions/77251296/distutils-not-found-when-running-npm-install
      PYTHON: 3.11
      # "$Env:GYP_MSVS_VERSION": 2022
    steps:
    - name: Install ubuntu requirements
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y libx11-dev libxss-dev icnsutils graphicsmagick libappindicator1 libxtst-dev
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
    - name: Specify MSVS version
      if: ${{ matrix.os == 'windows-latest' }}
      shell: powershell
      run: |
        echo "GYP_MSVS_VERSION=2022" >> $env:GITHUB_ENV

    # - name: Patch node-gyp
    #   if: ${{ matrix.os == 'windows-latest' }}
    #   shell: powershell
    #   run: |
    #     npm config set msvs_version 2022
    - run: npm ci
    - run: npm run test-lib
    - name: Run integration tests
      if: ${{ matrix.os != 'ubuntu-latest' }}
      run: npm run test-ui
    - uses: actions/upload-artifact@v3
      with:
        name: logs
        path: |
          # ~/.config/Before Dawn/logs/
          /Users/runner/Library/Logs/mocha/
          # C:\Users\runneradmin\AppData\Roaming\mocha\logs\
