name: Run tests
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-11, macos-12]
        node-version: [16.x]
    env:
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
    steps:
    - name: Install ubuntu requirements
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y libx11-dev libxss-dev icnsutils graphicsmagick libappindicator1 libxtst-dev
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Patch node-gyp
      if: ${{ matrix.os == 'windows-latest' }}
      shell: powershell
      run: |
        npm install --global node-gyp@latest
        npm prefix -g | % {npm config set node_gyp "$_\node_modules\node-gyp\bin\node-gyp.js"}
    - run: npm ci
    - run: npm run test-lib
    - name: Run integration tests
      if: ${{ matrix.os != 'ubuntu-latest' }}
      run: npm run test-ui
