name: Run tests
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest]
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Get yarn cache directory
      id: yarn-cache
      run: |
        echo "::set-output name=dir::$(yarn config get cache)"
    - uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Setup
      run: yarn
    - run: yarn test-lib
    - run: yarn test-ui
