name: eslint

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  eslint:
    # Name the Job
    name: Run eslint
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    steps:
      - name: Install ubuntu requirements
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y libx11-dev libxss-dev icnsutils graphicsmagick libappindicator1 libxtst-dev

      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Setup code
        run: npm i
      - name: Run eslint
        run: npm run eslint-all
