name: Build release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [12.x]
    steps:
    - name: Install ubuntu requirements
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y libx11-dev libxss-dev icnsutils graphicsmagick libappindicator1 libxtst-dev
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Get yarn cache directory
      id: yarn-cache
      run: |
        echo "::set-output name=dir::$(yarn config get cache)"
    - name: Build
      run: yarn
    - name: Release
    - run: yarn release
